// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/example.proto

package test_example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	_ "proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	// request body
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Response struct {
	// response body
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "test.example.Request")
	proto.RegisterType((*Response)(nil), "test.example.Response")
}

func init() { proto.RegisterFile("example/example.proto", fileDescriptor_1c78cffa5d645ba4) }

var fileDescriptor_1c78cffa5d645ba4 = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x3c, 0x25, 0xa9,
	0xc5, 0x25, 0x7a, 0x50, 0x31, 0x29, 0x7e, 0xb0, 0xa0, 0x7e, 0x6a, 0x45, 0x09, 0x44, 0x5a, 0x49,
	0x9a, 0x8b, 0x3d, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48, 0x80, 0x8b, 0x39, 0xb7, 0x38,
	0x5d, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x54, 0x92, 0xe1, 0xe2, 0x08, 0x4a, 0x2d,
	0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xc5, 0x94, 0x35, 0x6a, 0x62, 0xe2, 0x62, 0x0f, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0x15, 0xf2, 0xe6, 0xe2, 0x0a, 0xce, 0xcf, 0x4d, 0xf5, 0x4d, 0x2d, 0xc9, 0xc8,
	0x4f, 0x11, 0x12, 0xd5, 0x43, 0xb6, 0x54, 0x0f, 0x6a, 0x81, 0x94, 0x18, 0xba, 0x30, 0xc4, 0x68,
	0x25, 0xbe, 0x4b, 0x5b, 0x98, 0xb8, 0x1c, 0x53, 0x72, 0x33, 0xf3, 0x74, 0x42, 0x8b, 0x53, 0x8b,
	0x84, 0x82, 0xb8, 0x04, 0x41, 0x86, 0x39, 0xe6, 0xe5, 0x97, 0x64, 0xa4, 0x16, 0x51, 0x60, 0x66,
	0x70, 0x69, 0x41, 0x6a, 0x11, 0xd8, 0x60, 0xa1, 0x30, 0x2e, 0x61, 0x90, 0x99, 0x2e, 0x99, 0x69,
	0x69, 0xa9, 0x45, 0xa9, 0x79, 0x25, 0xe4, 0x99, 0x2a, 0x70, 0x69, 0x0b, 0x13, 0x0f, 0xc8, 0x8d,
	0x3a, 0xa1, 0x79, 0xd9, 0x79, 0xf9, 0xe5, 0x79, 0x49, 0x6c, 0xe0, 0x60, 0x34, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x09, 0x7c, 0x02, 0xe8, 0x7e, 0x01, 0x00, 0x00,
}
