// Code generated by protoc-gen-example. DO NOT EDIT.
package test_example
import (
	proto "github.com/golang/protobuf/proto"	
)

const _ = proto.ProtoPackageIsVersion3
var rolesMap = map[string][]string{	
	"/test_example.Service/SomeMethod": {"Admin", "User"},	
	"/test_example.Service/SomeAnotherMethod": {"SuperAdmin"},	
	"/test_example.Service/SomeDifferentMethod": {"User", "Unknown"},	
}

func CheckRole(method, role string)bool{
	v, ok := rolesMap[method]	
	if !ok {	
		return false	
	}	
	for _, roleToCheck := range v {	
		if role == roleToCheck {		
			return true		
		}		
	}	
	return false
}