// Code generated by protoc-gen-example. DO NOT EDIT.
package pb


var rolesMap = map[string][]string{	
	"/test_example.Service/SomeAnotherMethod": {"SuperAdmin"},	
	"/test_example.Service/SomeDifferentMethod": {"User", "Unknown"},	
	"/test_example.Service/SomeMethod": {"Admin", "User"},	
}

func CheckRole(method, role string)bool{
	v, ok := rolesMap[method]	
	if !ok {	
		// If there is no method in the map then it's not protected		
		return true	
	}	
	for _, roleToCheck := range v {	
		if role == roleToCheck {		
			return true		
		}		
	}	
	return false
}